services:
  db:
    image: postgres:16-alpine
    container_name: ekvator_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT: ${JWT}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: dinarsharipov/ekvator:latest
    container_name: ekvator_app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
